### PR TITLE
Redesigned documentation structure

### LINKED ISSUE #5: Tutorials aren't being generated
If you look for the tutorials in the generated docs they're not there. This only happens with this specific theme. I tried using the default theme and tutorials get generated in that case.

### PR DESCRIPTION
**Pull request by ricardograca**
This changes the current single-page documentation to a new multi-page structure with the Readme, API Reference and Tutorials all on separate pages.

The home page is now composed from the Readme and Changelog.

Tutorials are now being generated as separate files and can be linked to from other doclets (Fixes #5).

### Additional changes and bug fixes

- Updates dependencies
- Fixes outdated and/or incorrect fields on `package.json`
- Fixes wonky looking changelog style
- Removes some unused code
- Removes method `@example` code gap after the method's signature
- In the unlikely event that horizontal page content overflows the page width (on very narrow screens) the overflown content will now be hidden
- Method signatures now can have multiple lines in case the content doesn't fit in a single one

#### Home page

captura de ecra 2018-11-03 as 19 58 09

#### Tutorials/Guides

captura de ecra 2018-11-03 as 19 57 58

#### API Reference

captura de ecra 2018-11-03 as 19 57 48

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Nice. FYI I originally made this theme because Tim requested that everything go on one page so you can use find "find" feature of the browser.

**Comment by ricardograca** [comment]
Nice to know! You can still do that since the API reference is all on a single page and I have no intention of changing that.

**Comment by rhys-vdw** [comment]
Excellent.

**Comment by kirrg001** [comment]
👍

**Pull request merged**
